Add explicit braces, C++ casts, WITH_WARNINGS build option
tenacityteam/portsmf pull request #6
Opened 2021-07-20 06:21 UTC by Veratil

* Bump minimum CMake version to 3.1, noticed this is minimum for `CMAKE_CXX_STANDARD`
* Add the `WITH_WARNINGS` build option I've been using for testing various warning flags (using `/W4` for MSVC since I saw somewhere that's a similar level for `-Wall -Wextra`)
* Add explicit braces where missing, pretty sure I got them all
* Update to C++ style casts as best as I could, there's a lot of C style casting that just doesn't fly well with C++

The `WITH_WARNINGS` I made work with gcc and clang (including macOS clang) and threw in the MSVC branch for when we can test that better.

Apologies for the braces and C++ casts together in the same commit. I was going through all lines by hand and just did it at the same time.

2021-07-20 07:20 UTC, Veratil commented
Hold off on merge for now. I want to get a better test done with this build first. I can do that tomorrow. 👍

2021-07-20 14:53 UTC, Veratil commented
Alright I've tested this build with LMMS (embedded not library yet). MIDI imports are still working as before. I'm confident about the casts. 👍

2021-07-22 01:27 UTC, Be-ing commented on CMakeLists.txt
> +if (WITH_WARNINGS)
```suggestion
if(WITH_WARNINGS)
```
for consistency

2021-07-22 01:28 UTC, Be-ing requested changes

2021-07-22 01:28 UTC, Be-ing commented on CMakeLists.txt
> +if (WITH_WARNINGS)
also change below

2021-07-22 01:30 UTC, Be-ing commented on include/allegro.h
> +        if (--refcount <= 0) {
aaa more mutating variables in conditional expressions. Please separate this from the conditional expression

2021-07-22 01:39 UTC, Be-ing commented on CMakeLists.txt
> +option(WITH_WARNINGS "Build with compiler warnings enabled" OFF)
If it builds without warnings, let's not make this an option and just always turn on warnings.

2021-07-22 01:55 UTC, Be-ing commented
Thank you for doing this tedious cleanup.

2021-07-22 02:04 UTC, Veratil commented on CMakeLists.txt
> +option(WITH_WARNINGS "Build with compiler warnings enabled" OFF)
Done!

2021-07-22 02:05 UTC, Veratil commented on include/allegro.h
> +        if (--refcount <= 0) {
oops it inserted a tab instead of spaces again :joy: gotta fix that in my vim config lol

2021-07-22 02:07 UTC, Veratil commented
Okay! Now it all should be good. 😂

2021-07-22 02:09 UTC, Veratil commented
Oh I should probably rename the first commit

2021-07-22 02:14 UTC, Veratil commented
Lots of warnings in MSVC, but nothing that's breaking.

2021-07-22 12:58 UTC, merged

2021-07-23 01:10 UTC, Be-ing commented
Let me know when you're done with the cleanups you want to do and I'll tag a release.

2021-07-23 02:15 UTC, Veratil commented
Currently working on adding Doxygen. It won't be *good* initial documentation since it's kind of "these groups of functions do this" or there just isn't any, but it'll be a stepping point.

2021-08-06 17:02 UTC, Be-ing commented
@Veratil my [PR to package PortSMF for upstream vcpkg](https://github.com/microsoft/vcpkg/pull/18982) was merged.